//
//Copyright (C) 2022 Jake Sanders
//
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU Affero General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU Affero General Public License for more details.
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/mgmt/v1/mgmt.proto

package mgmtv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignerType int32

const (
	SignerType_SIGNER_TYPE_UNSPECIFIED SignerType = 0
	SignerType_SIGNER_TYPE_INMEM       SignerType = 1
	SignerType_SIGNER_TYPE_FILE        SignerType = 2
	SignerType_SIGNER_TYPE_HSM         SignerType = 3
	SignerType_SIGNER_TYPE_REMOTE      SignerType = 4
)

// Enum value maps for SignerType.
var (
	SignerType_name = map[int32]string{
		0: "SIGNER_TYPE_UNSPECIFIED",
		1: "SIGNER_TYPE_INMEM",
		2: "SIGNER_TYPE_FILE",
		3: "SIGNER_TYPE_HSM",
		4: "SIGNER_TYPE_REMOTE",
	}
	SignerType_value = map[string]int32{
		"SIGNER_TYPE_UNSPECIFIED": 0,
		"SIGNER_TYPE_INMEM":       1,
		"SIGNER_TYPE_FILE":        2,
		"SIGNER_TYPE_HSM":         3,
		"SIGNER_TYPE_REMOTE":      4,
	}
)

func (x SignerType) Enum() *SignerType {
	p := new(SignerType)
	*p = x
	return p
}

func (x SignerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignerType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mgmt_v1_mgmt_proto_enumTypes[0].Descriptor()
}

func (SignerType) Type() protoreflect.EnumType {
	return &file_api_mgmt_v1_mgmt_proto_enumTypes[0]
}

func (x SignerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignerType.Descriptor instead.
func (SignerType) EnumDescriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{0}
}

type PrivateKeyType int32

const (
	PrivateKeyType_PRIVATE_KEY_TYPE_UNSPECIFIED PrivateKeyType = 0
	PrivateKeyType_PRIVATE_KEY_TYPE_RSA         PrivateKeyType = 1
	PrivateKeyType_PRIVATE_KEY_TYPE_EC          PrivateKeyType = 2
	PrivateKeyType_PRIVATE_KEY_TYPE_ED25519     PrivateKeyType = 3
)

// Enum value maps for PrivateKeyType.
var (
	PrivateKeyType_name = map[int32]string{
		0: "PRIVATE_KEY_TYPE_UNSPECIFIED",
		1: "PRIVATE_KEY_TYPE_RSA",
		2: "PRIVATE_KEY_TYPE_EC",
		3: "PRIVATE_KEY_TYPE_ED25519",
	}
	PrivateKeyType_value = map[string]int32{
		"PRIVATE_KEY_TYPE_UNSPECIFIED": 0,
		"PRIVATE_KEY_TYPE_RSA":         1,
		"PRIVATE_KEY_TYPE_EC":          2,
		"PRIVATE_KEY_TYPE_ED25519":     3,
	}
)

func (x PrivateKeyType) Enum() *PrivateKeyType {
	p := new(PrivateKeyType)
	*p = x
	return p
}

func (x PrivateKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivateKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mgmt_v1_mgmt_proto_enumTypes[1].Descriptor()
}

func (PrivateKeyType) Type() protoreflect.EnumType {
	return &file_api_mgmt_v1_mgmt_proto_enumTypes[1]
}

func (x PrivateKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivateKeyType.Descriptor instead.
func (PrivateKeyType) EnumDescriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{1}
}

type RemoteType int32

const (
	RemoteType_REMOTE_TYPE_UNSPECIFIED RemoteType = 0
	// Use the another already available northfoot to sign a CSR
	RemoteType_REMOTE_TYPE_NORTHFOOT RemoteType = 1
	// Use a PEM cert / key received verbatim over https
	RemoteType_REMOTE_TYPE_VERBATIM_HTTPS RemoteType = 2
)

// Enum value maps for RemoteType.
var (
	RemoteType_name = map[int32]string{
		0: "REMOTE_TYPE_UNSPECIFIED",
		1: "REMOTE_TYPE_NORTHFOOT",
		2: "REMOTE_TYPE_VERBATIM_HTTPS",
	}
	RemoteType_value = map[string]int32{
		"REMOTE_TYPE_UNSPECIFIED":    0,
		"REMOTE_TYPE_NORTHFOOT":      1,
		"REMOTE_TYPE_VERBATIM_HTTPS": 2,
	}
)

func (x RemoteType) Enum() *RemoteType {
	p := new(RemoteType)
	*p = x
	return p
}

func (x RemoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mgmt_v1_mgmt_proto_enumTypes[2].Descriptor()
}

func (RemoteType) Type() protoreflect.EnumType {
	return &file_api_mgmt_v1_mgmt_proto_enumTypes[2]
}

func (x RemoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteType.Descriptor instead.
func (RemoteType) EnumDescriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{2}
}

type Signer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *int64     `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name        *string    `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description *string    `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Type        SignerType `protobuf:"varint,4,opt,name=type,proto3,enum=api.mgmt.v1.SignerType" json:"type,omitempty"`
	// Types that are assignable to SignerConfig:
	//	*Signer_InMem
	//	*Signer_File
	//	*Signer_Hsm
	//	*Signer_Remote
	SignerConfig isSigner_SignerConfig `protobuf_oneof:"signer_config"`
}

func (x *Signer) Reset() {
	*x = Signer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signer) ProtoMessage() {}

func (x *Signer) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signer.ProtoReflect.Descriptor instead.
func (*Signer) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{0}
}

func (x *Signer) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Signer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Signer) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Signer) GetType() SignerType {
	if x != nil {
		return x.Type
	}
	return SignerType_SIGNER_TYPE_UNSPECIFIED
}

func (m *Signer) GetSignerConfig() isSigner_SignerConfig {
	if m != nil {
		return m.SignerConfig
	}
	return nil
}

func (x *Signer) GetInMem() *SignerInMemConfig {
	if x, ok := x.GetSignerConfig().(*Signer_InMem); ok {
		return x.InMem
	}
	return nil
}

func (x *Signer) GetFile() *SignerFileConfig {
	if x, ok := x.GetSignerConfig().(*Signer_File); ok {
		return x.File
	}
	return nil
}

func (x *Signer) GetHsm() *SignerHSMConfig {
	if x, ok := x.GetSignerConfig().(*Signer_Hsm); ok {
		return x.Hsm
	}
	return nil
}

func (x *Signer) GetRemote() *SignerRemoteConfig {
	if x, ok := x.GetSignerConfig().(*Signer_Remote); ok {
		return x.Remote
	}
	return nil
}

type isSigner_SignerConfig interface {
	isSigner_SignerConfig()
}

type Signer_InMem struct {
	InMem *SignerInMemConfig `protobuf:"bytes,5,opt,name=in_mem,json=inMem,proto3,oneof"`
}

type Signer_File struct {
	File *SignerFileConfig `protobuf:"bytes,6,opt,name=file,proto3,oneof"`
}

type Signer_Hsm struct {
	Hsm *SignerHSMConfig `protobuf:"bytes,7,opt,name=hsm,proto3,oneof"`
}

type Signer_Remote struct {
	Remote *SignerRemoteConfig `protobuf:"bytes,8,opt,name=remote,proto3,oneof"`
}

func (*Signer_InMem) isSigner_SignerConfig() {}

func (*Signer_File) isSigner_SignerConfig() {}

func (*Signer_Hsm) isSigner_SignerConfig() {}

func (*Signer_Remote) isSigner_SignerConfig() {}

type SignerInMemConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key type to generate in memory
	Key     PrivateKeyType `protobuf:"varint,1,opt,name=key,proto3,enum=api.mgmt.v1.PrivateKeyType" json:"key,omitempty"`
	KeySize *int64         `protobuf:"varint,2,opt,name=key_size,json=keySize,proto3,oneof" json:"key_size,omitempty"`
}

func (x *SignerInMemConfig) Reset() {
	*x = SignerInMemConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerInMemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerInMemConfig) ProtoMessage() {}

func (x *SignerInMemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerInMemConfig.ProtoReflect.Descriptor instead.
func (*SignerInMemConfig) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{1}
}

func (x *SignerInMemConfig) GetKey() PrivateKeyType {
	if x != nil {
		return x.Key
	}
	return PrivateKeyType_PRIVATE_KEY_TYPE_UNSPECIFIED
}

func (x *SignerInMemConfig) GetKeySize() int64 {
	if x != nil && x.KeySize != nil {
		return *x.KeySize
	}
	return 0
}

type SignerFileConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TlsCertFilePath string `protobuf:"bytes,1,opt,name=tls_cert_file_path,json=tlsCertFilePath,proto3" json:"tls_cert_file_path,omitempty"`
	TlsKeyFilePath  string `protobuf:"bytes,2,opt,name=tls_key_file_path,json=tlsKeyFilePath,proto3" json:"tls_key_file_path,omitempty"`
}

func (x *SignerFileConfig) Reset() {
	*x = SignerFileConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerFileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerFileConfig) ProtoMessage() {}

func (x *SignerFileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerFileConfig.ProtoReflect.Descriptor instead.
func (*SignerFileConfig) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{2}
}

func (x *SignerFileConfig) GetTlsCertFilePath() string {
	if x != nil {
		return x.TlsCertFilePath
	}
	return ""
}

func (x *SignerFileConfig) GetTlsKeyFilePath() string {
	if x != nil {
		return x.TlsKeyFilePath
	}
	return ""
}

type SignerHSMConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HsmLibraryPath string  `protobuf:"bytes,1,opt,name=hsm_library_path,json=hsmLibraryPath,proto3" json:"hsm_library_path,omitempty"`
	HsmTokenSerial *string `protobuf:"bytes,2,opt,name=hsm_token_serial,json=hsmTokenSerial,proto3,oneof" json:"hsm_token_serial,omitempty"`
	HsmTokenLabel  *string `protobuf:"bytes,3,opt,name=hsm_token_label,json=hsmTokenLabel,proto3,oneof" json:"hsm_token_label,omitempty"`
	HsmTokenPin    *string `protobuf:"bytes,4,opt,name=hsm_token_pin,json=hsmTokenPin,proto3,oneof" json:"hsm_token_pin,omitempty"`
}

func (x *SignerHSMConfig) Reset() {
	*x = SignerHSMConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerHSMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerHSMConfig) ProtoMessage() {}

func (x *SignerHSMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerHSMConfig.ProtoReflect.Descriptor instead.
func (*SignerHSMConfig) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{3}
}

func (x *SignerHSMConfig) GetHsmLibraryPath() string {
	if x != nil {
		return x.HsmLibraryPath
	}
	return ""
}

func (x *SignerHSMConfig) GetHsmTokenSerial() string {
	if x != nil && x.HsmTokenSerial != nil {
		return *x.HsmTokenSerial
	}
	return ""
}

func (x *SignerHSMConfig) GetHsmTokenLabel() string {
	if x != nil && x.HsmTokenLabel != nil {
		return *x.HsmTokenLabel
	}
	return ""
}

func (x *SignerHSMConfig) GetHsmTokenPin() string {
	if x != nil && x.HsmTokenPin != nil {
		return *x.HsmTokenPin
	}
	return ""
}

type RemoteNorthfootConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
}

func (x *RemoteNorthfootConfig) Reset() {
	*x = RemoteNorthfootConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteNorthfootConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteNorthfootConfig) ProtoMessage() {}

func (x *RemoteNorthfootConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteNorthfootConfig.ProtoReflect.Descriptor instead.
func (*RemoteNorthfootConfig) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{4}
}

func (x *RemoteNorthfootConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RemoteVerbatimHttpsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertUrl string `protobuf:"bytes,1,opt,name=cert_url,json=certUrl,proto3" json:"cert_url,omitempty"`
	KeyUrl  string `protobuf:"bytes,2,opt,name=key_url,json=keyUrl,proto3" json:"key_url,omitempty"`
}

func (x *RemoteVerbatimHttpsConfig) Reset() {
	*x = RemoteVerbatimHttpsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteVerbatimHttpsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteVerbatimHttpsConfig) ProtoMessage() {}

func (x *RemoteVerbatimHttpsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteVerbatimHttpsConfig.ProtoReflect.Descriptor instead.
func (*RemoteVerbatimHttpsConfig) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteVerbatimHttpsConfig) GetCertUrl() string {
	if x != nil {
		return x.CertUrl
	}
	return ""
}

func (x *RemoteVerbatimHttpsConfig) GetKeyUrl() string {
	if x != nil {
		return x.KeyUrl
	}
	return ""
}

type SignerRemoteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteType RemoteType `protobuf:"varint,1,opt,name=remote_type,json=remoteType,proto3,enum=api.mgmt.v1.RemoteType" json:"remote_type,omitempty"`
	// Types that are assignable to RemoteConfig:
	//	*SignerRemoteConfig_Northfoot
	//	*SignerRemoteConfig_VerbatimHttps
	RemoteConfig isSignerRemoteConfig_RemoteConfig `protobuf_oneof:"remote_config"`
}

func (x *SignerRemoteConfig) Reset() {
	*x = SignerRemoteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerRemoteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerRemoteConfig) ProtoMessage() {}

func (x *SignerRemoteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerRemoteConfig.ProtoReflect.Descriptor instead.
func (*SignerRemoteConfig) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{6}
}

func (x *SignerRemoteConfig) GetRemoteType() RemoteType {
	if x != nil {
		return x.RemoteType
	}
	return RemoteType_REMOTE_TYPE_UNSPECIFIED
}

func (m *SignerRemoteConfig) GetRemoteConfig() isSignerRemoteConfig_RemoteConfig {
	if m != nil {
		return m.RemoteConfig
	}
	return nil
}

func (x *SignerRemoteConfig) GetNorthfoot() *RemoteNorthfootConfig {
	if x, ok := x.GetRemoteConfig().(*SignerRemoteConfig_Northfoot); ok {
		return x.Northfoot
	}
	return nil
}

func (x *SignerRemoteConfig) GetVerbatimHttps() *RemoteVerbatimHttpsConfig {
	if x, ok := x.GetRemoteConfig().(*SignerRemoteConfig_VerbatimHttps); ok {
		return x.VerbatimHttps
	}
	return nil
}

type isSignerRemoteConfig_RemoteConfig interface {
	isSignerRemoteConfig_RemoteConfig()
}

type SignerRemoteConfig_Northfoot struct {
	Northfoot *RemoteNorthfootConfig `protobuf:"bytes,2,opt,name=northfoot,proto3,oneof"`
}

type SignerRemoteConfig_VerbatimHttps struct {
	VerbatimHttps *RemoteVerbatimHttpsConfig `protobuf:"bytes,3,opt,name=verbatim_https,json=verbatimHttps,proto3,oneof"`
}

func (*SignerRemoteConfig_Northfoot) isSignerRemoteConfig_RemoteConfig() {}

func (*SignerRemoteConfig_VerbatimHttps) isSignerRemoteConfig_RemoteConfig() {}

type GetSignerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSignerRequest) Reset() {
	*x = GetSignerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerRequest) ProtoMessage() {}

func (x *GetSignerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerRequest.ProtoReflect.Descriptor instead.
func (*GetSignerRequest) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{7}
}

func (x *GetSignerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSignerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer *Signer `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (x *GetSignerResponse) Reset() {
	*x = GetSignerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerResponse) ProtoMessage() {}

func (x *GetSignerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerResponse.ProtoReflect.Descriptor instead.
func (*GetSignerResponse) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{8}
}

func (x *GetSignerResponse) GetSigner() *Signer {
	if x != nil {
		return x.Signer
	}
	return nil
}

type SignerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signers []*Signer `protobuf:"bytes,1,rep,name=signers,proto3" json:"signers,omitempty"`
}

func (x *SignerList) Reset() {
	*x = SignerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerList) ProtoMessage() {}

func (x *SignerList) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerList.ProtoReflect.Descriptor instead.
func (*SignerList) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{9}
}

func (x *SignerList) GetSigners() []*Signer {
	if x != nil {
		return x.Signers
	}
	return nil
}

type ListSignersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signers *SignerList `protobuf:"bytes,1,opt,name=signers,proto3" json:"signers,omitempty"`
}

func (x *ListSignersResponse) Reset() {
	*x = ListSignersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSignersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSignersResponse) ProtoMessage() {}

func (x *ListSignersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSignersResponse.ProtoReflect.Descriptor instead.
func (*ListSignersResponse) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{10}
}

func (x *ListSignersResponse) GetSigners() *SignerList {
	if x != nil {
		return x.Signers
	}
	return nil
}

type CreateSignerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer *Signer `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (x *CreateSignerRequest) Reset() {
	*x = CreateSignerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSignerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignerRequest) ProtoMessage() {}

func (x *CreateSignerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignerRequest.ProtoReflect.Descriptor instead.
func (*CreateSignerRequest) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSignerRequest) GetSigner() *Signer {
	if x != nil {
		return x.Signer
	}
	return nil
}

type DeleteSignerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSignerRequest) Reset() {
	*x = DeleteSignerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSignerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSignerRequest) ProtoMessage() {}

func (x *DeleteSignerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mgmt_v1_mgmt_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSignerRequest.ProtoReflect.Descriptor instead.
func (*DeleteSignerRequest) Descriptor() ([]byte, []int) {
	return file_api_mgmt_v1_mgmt_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSignerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_mgmt_v1_mgmt_proto protoreflect.FileDescriptor

var file_api_mgmt_v1_mgmt_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x96, 0x03, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x13, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x02, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x69, 0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x4d, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48,
	0x00, 0x52, 0x05, 0x69, 0x6e, 0x4d, 0x65, 0x6d, 0x12, 0x33, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x30, 0x0a,
	0x03, 0x68, 0x73, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x48,
	0x53, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x03, 0x68, 0x73, 0x6d, 0x12,
	0x39, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6f, 0x0a, 0x11, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x4d, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x2d, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1e, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x6a, 0x0a, 0x10,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x2b, 0x0a, 0x12, 0x74, 0x6c, 0x73, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6c,
	0x73, 0x43, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a,
	0x11, 0x74, 0x6c, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x6c, 0x73, 0x4b, 0x65, 0x79,
	0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0xfb, 0x01, 0x0a, 0x0f, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x48, 0x53, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28, 0x0a, 0x10,
	0x68, 0x73, 0x6d, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x73, 0x6d, 0x4c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x10, 0x68, 0x73, 0x6d, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0e, 0x68, 0x73, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0f, 0x68, 0x73, 0x6d, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0d, 0x68, 0x73, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x27, 0x0a, 0x0d, 0x68, 0x73, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x70, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0b, 0x68, 0x73, 0x6d,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f,
	0x68, 0x73, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x42, 0x12, 0x0a, 0x10, 0x5f, 0x68, 0x73, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x68, 0x73, 0x6d, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x70, 0x69, 0x6e, 0x22, 0x33, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x4e, 0x6f, 0x72, 0x74, 0x68, 0x66, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x19, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x56, 0x65, 0x72, 0x62, 0x61, 0x74, 0x69, 0x6d, 0x48, 0x74, 0x74,
	0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x65, 0x72, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x65, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x55, 0x72, 0x6c, 0x22, 0xf4, 0x01, 0x0a,
	0x12, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a,
	0x09, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x66, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4e, 0x6f, 0x72, 0x74, 0x68, 0x66, 0x6f, 0x6f, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x66, 0x6f, 0x6f,
	0x74, 0x12, 0x4f, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x62, 0x61, 0x74, 0x69, 0x6d, 0x5f, 0x68, 0x74,
	0x74, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x56, 0x65,
	0x72, 0x62, 0x61, 0x74, 0x69, 0x6d, 0x48, 0x74, 0x74, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x48, 0x00, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x62, 0x61, 0x74, 0x69, 0x6d, 0x48, 0x74, 0x74,
	0x70, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0a, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x07, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x48, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x07, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73,
	0x22, 0x42, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x83, 0x01, 0x0a, 0x0a,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x49,
	0x47, 0x4e, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x49, 0x47, 0x4e, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x4d, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x53, 0x49, 0x47, 0x4e, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x49, 0x47, 0x4e, 0x45, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x48, 0x53, 0x4d, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x49, 0x47,
	0x4e, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x10,
	0x04, 0x2a, 0x83, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x5f,
	0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54,
	0x45, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x53, 0x41, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x43, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x49,
	0x56, 0x41, 0x54, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x44,
	0x32, 0x35, 0x35, 0x31, 0x39, 0x10, 0x03, 0x2a, 0x64, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x46, 0x4f, 0x4f, 0x54, 0x10, 0x01, 0x12, 0x1e, 0x0a,
	0x1a, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x45, 0x52,
	0x42, 0x41, 0x54, 0x49, 0x4d, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x53, 0x10, 0x02, 0x32, 0xbc, 0x02,
	0x0a, 0x11, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x48, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x31, 0x5a, 0x2f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x6b, 0x65, 0x78,
	0x6b, 0x73, 0x2f, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x66, 0x6f, 0x6f, 0x74, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x67, 0x6d, 0x74, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mgmt_v1_mgmt_proto_rawDescOnce sync.Once
	file_api_mgmt_v1_mgmt_proto_rawDescData = file_api_mgmt_v1_mgmt_proto_rawDesc
)

func file_api_mgmt_v1_mgmt_proto_rawDescGZIP() []byte {
	file_api_mgmt_v1_mgmt_proto_rawDescOnce.Do(func() {
		file_api_mgmt_v1_mgmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mgmt_v1_mgmt_proto_rawDescData)
	})
	return file_api_mgmt_v1_mgmt_proto_rawDescData
}

var file_api_mgmt_v1_mgmt_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_mgmt_v1_mgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_mgmt_v1_mgmt_proto_goTypes = []interface{}{
	(SignerType)(0),                   // 0: api.mgmt.v1.SignerType
	(PrivateKeyType)(0),               // 1: api.mgmt.v1.PrivateKeyType
	(RemoteType)(0),                   // 2: api.mgmt.v1.RemoteType
	(*Signer)(nil),                    // 3: api.mgmt.v1.Signer
	(*SignerInMemConfig)(nil),         // 4: api.mgmt.v1.SignerInMemConfig
	(*SignerFileConfig)(nil),          // 5: api.mgmt.v1.SignerFileConfig
	(*SignerHSMConfig)(nil),           // 6: api.mgmt.v1.SignerHSMConfig
	(*RemoteNorthfootConfig)(nil),     // 7: api.mgmt.v1.RemoteNorthfootConfig
	(*RemoteVerbatimHttpsConfig)(nil), // 8: api.mgmt.v1.RemoteVerbatimHttpsConfig
	(*SignerRemoteConfig)(nil),        // 9: api.mgmt.v1.SignerRemoteConfig
	(*GetSignerRequest)(nil),          // 10: api.mgmt.v1.GetSignerRequest
	(*GetSignerResponse)(nil),         // 11: api.mgmt.v1.GetSignerResponse
	(*SignerList)(nil),                // 12: api.mgmt.v1.SignerList
	(*ListSignersResponse)(nil),       // 13: api.mgmt.v1.ListSignersResponse
	(*CreateSignerRequest)(nil),       // 14: api.mgmt.v1.CreateSignerRequest
	(*DeleteSignerRequest)(nil),       // 15: api.mgmt.v1.DeleteSignerRequest
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
}
var file_api_mgmt_v1_mgmt_proto_depIdxs = []int32{
	0,  // 0: api.mgmt.v1.Signer.type:type_name -> api.mgmt.v1.SignerType
	4,  // 1: api.mgmt.v1.Signer.in_mem:type_name -> api.mgmt.v1.SignerInMemConfig
	5,  // 2: api.mgmt.v1.Signer.file:type_name -> api.mgmt.v1.SignerFileConfig
	6,  // 3: api.mgmt.v1.Signer.hsm:type_name -> api.mgmt.v1.SignerHSMConfig
	9,  // 4: api.mgmt.v1.Signer.remote:type_name -> api.mgmt.v1.SignerRemoteConfig
	1,  // 5: api.mgmt.v1.SignerInMemConfig.key:type_name -> api.mgmt.v1.PrivateKeyType
	2,  // 6: api.mgmt.v1.SignerRemoteConfig.remote_type:type_name -> api.mgmt.v1.RemoteType
	7,  // 7: api.mgmt.v1.SignerRemoteConfig.northfoot:type_name -> api.mgmt.v1.RemoteNorthfootConfig
	8,  // 8: api.mgmt.v1.SignerRemoteConfig.verbatim_https:type_name -> api.mgmt.v1.RemoteVerbatimHttpsConfig
	3,  // 9: api.mgmt.v1.GetSignerResponse.signer:type_name -> api.mgmt.v1.Signer
	3,  // 10: api.mgmt.v1.SignerList.signers:type_name -> api.mgmt.v1.Signer
	12, // 11: api.mgmt.v1.ListSignersResponse.signers:type_name -> api.mgmt.v1.SignerList
	3,  // 12: api.mgmt.v1.CreateSignerRequest.signer:type_name -> api.mgmt.v1.Signer
	10, // 13: api.mgmt.v1.ManagementService.GetSigner:input_type -> api.mgmt.v1.GetSignerRequest
	16, // 14: api.mgmt.v1.ManagementService.ListSigners:input_type -> google.protobuf.Empty
	14, // 15: api.mgmt.v1.ManagementService.CreateSigner:input_type -> api.mgmt.v1.CreateSignerRequest
	15, // 16: api.mgmt.v1.ManagementService.DeleteSigner:input_type -> api.mgmt.v1.DeleteSignerRequest
	11, // 17: api.mgmt.v1.ManagementService.GetSigner:output_type -> api.mgmt.v1.GetSignerResponse
	13, // 18: api.mgmt.v1.ManagementService.ListSigners:output_type -> api.mgmt.v1.ListSignersResponse
	16, // 19: api.mgmt.v1.ManagementService.CreateSigner:output_type -> google.protobuf.Empty
	16, // 20: api.mgmt.v1.ManagementService.DeleteSigner:output_type -> google.protobuf.Empty
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_mgmt_v1_mgmt_proto_init() }
func file_api_mgmt_v1_mgmt_proto_init() {
	if File_api_mgmt_v1_mgmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mgmt_v1_mgmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerInMemConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerFileConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerHSMConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteNorthfootConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteVerbatimHttpsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerRemoteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSignersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSignerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mgmt_v1_mgmt_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSignerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_mgmt_v1_mgmt_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Signer_InMem)(nil),
		(*Signer_File)(nil),
		(*Signer_Hsm)(nil),
		(*Signer_Remote)(nil),
	}
	file_api_mgmt_v1_mgmt_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_mgmt_v1_mgmt_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_api_mgmt_v1_mgmt_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*SignerRemoteConfig_Northfoot)(nil),
		(*SignerRemoteConfig_VerbatimHttps)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mgmt_v1_mgmt_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mgmt_v1_mgmt_proto_goTypes,
		DependencyIndexes: file_api_mgmt_v1_mgmt_proto_depIdxs,
		EnumInfos:         file_api_mgmt_v1_mgmt_proto_enumTypes,
		MessageInfos:      file_api_mgmt_v1_mgmt_proto_msgTypes,
	}.Build()
	File_api_mgmt_v1_mgmt_proto = out.File
	file_api_mgmt_v1_mgmt_proto_rawDesc = nil
	file_api_mgmt_v1_mgmt_proto_goTypes = nil
	file_api_mgmt_v1_mgmt_proto_depIdxs = nil
}
